language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules 
install:
  - yarn
script:
  - yarn build
after_success:
  - surge --project ./dist --domain grubby-requests.surge.sh